# Generated by Django 5.2.5 on 2026-01-04 09:54

from django.db import migrations


def clean_duplicate_emails(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    from django.db.models import Count
    duplicates = User.objects.values('email').annotate(count=Count('id')).filter(count__gt=1)
    for dup in duplicates:
        users_to_delete = User.objects.filter(email=dup['email']).order_by('id')[1:]
        for user in users_to_delete:
            user.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.RunPython(clean_duplicate_emails),
    ]
